version: "3.7"

services:
  db:
   image: mysql:5.6
   environment:
    MYSQL_ROOT_PASSWORD: nimda
    MYSQL_DATABASE: example_db
    MYSQL_USER: example_db_user
    MYSQL_PASSWORD: example_db_pass
   volumes:
    - ./db:/docker-entrypoint-initdb.d

  web:
   depends_on:
   - db
   image: tomcat:latest
   environment:
    JDBC_URL: jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: example_db_user
    JDBC_PASS: example_db_pass
   ports:
    - "80:8080"
   volumes:
    - ./tomcat/webapps:/usr/local/tomcat/webapps
   links:
    - db
